name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Firebase Configuration
        run: |
          echo "export default {" > firebaseConfig.js && \
          echo "  apiKey: '$FIREBASE_API_KEY'," >> firebaseConfig.js && \
          echo "  authDomain: '$FIREBASE_AUTH_DOMAIN'," >> firebaseConfig.js && \
          echo "  projectId: '$FIREBASE_PROJECT_ID'," >> firebaseConfig.js && \
          echo "  storageBucket: '$FIREBASE_STORAGE_BUCKET'," >> firebaseConfig.js && \
          echo "  messagingSenderId: '$FIREBASE_MESSAGING_SENDER_ID'," >> firebaseConfig.js && \
          echo "  appId: '$FIREBASE_APP_ID'" >> firebaseConfig.js && \
          echo "};" >> firebaseConfig.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
